# SPDX-License-Identifier: Apache-2.0
# Copyright The Robinauts Authors

"""What the check scripts do at their edges.

A gate that passes when its own tooling fails is worse than no gate, because
it is believed. The first half runs `scripts/check-audit.sh` against stand-in
`uv` and `uvx` commands that fail, or answer with too little, and expects a
red build every time. The second runs `scripts/check-dco.sh` over throwaway
repositories, for the sign-offs it must accept and the ones it must not.
"""

import os
import stat
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
AUDIT = ROOT / "scripts" / "check-audit.sh"

EXPORT = """\
# This file was autogenerated by uv via the following command:
#    uv export
black==26.5.1
colorama==0.4.6 ; sys_platform == 'win32'
"""

REPORT = '{"dependencies": [{"name": "black", "version": "26.5.1", "vulns": []}]}'


def _stub(directory: Path, name: str, script: str) -> None:
    command = directory / name
    command.write_text(f"#!/bin/sh\n{script}\n", encoding="utf-8")
    command.chmod(command.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _run(directory: Path):
    environment = dict(os.environ, PATH=f"{directory}{os.pathsep}{os.environ['PATH']}")
    return subprocess.run(
        [str(AUDIT)], capture_output=True, text=True, env=environment, cwd=str(ROOT)
    )


@pytest.mark.io
def test_an_export_that_fails_is_not_an_empty_audit(tmp_path):
    # The bug this guards: `uv export | sed >file` in a POSIX shell reports the
    # status of `sed`, so a stale lock left an empty file and a green build.
    _stub(tmp_path, "uv", 'echo "error: the lockfile is out of date" >&2\nexit 2')
    _stub(tmp_path, "uvx", 'echo "{\\"dependencies\\": []}"')

    result = _run(tmp_path)

    assert result.returncode != 0
    assert "audited" not in result.stdout


@pytest.mark.io
def test_an_export_that_pins_nothing_is_not_an_audit(tmp_path):
    _stub(tmp_path, "uv", 'echo "# nothing here"')
    _stub(tmp_path, "uvx", 'echo "{\\"dependencies\\": []}"')

    result = _run(tmp_path)

    assert result.returncode != 0
    assert "pinned no package at all" in result.stdout


@pytest.mark.io
def test_a_package_the_auditor_skipped_is_a_failure(tmp_path):
    # pip-audit drops what it cannot or will not look at, and says nothing.
    _stub(tmp_path, "uv", f"cat <<'EOF'\n{EXPORT}EOF")
    _stub(tmp_path, "uvx", f"cat <<'EOF'\n{REPORT}\nEOF")

    result = _run(tmp_path)

    assert result.returncode != 0
    assert "audited 1 of the 2 packages the lock pins" in result.stdout
    assert "not audited: colorama" in result.stdout


@pytest.mark.io
def test_a_package_the_auditor_refused_to_look_at_is_a_failure(tmp_path):
    # pip-audit reports what it skipped with a reason and no version at all.
    report = (
        '{"dependencies": ['
        '{"name": "black", "version": "26.5.1", "vulns": []},'
        '{"name": "colorama", "skip_reason": "not found on PyPI, could not be audited"}'
        "]}"
    )
    _stub(tmp_path, "uv", f"cat <<'EOF'\n{EXPORT}EOF")
    _stub(tmp_path, "uvx", f"cat <<'EOF'\n{report}\nEOF")

    result = _run(tmp_path)

    assert result.returncode != 0
    assert "pip-audit skipped 1 of the 2 packages" in result.stdout
    assert "colorama: not found on PyPI" in result.stdout


@pytest.mark.io
def test_a_vulnerability_is_reported_with_its_fix(tmp_path):
    report = (
        '{"dependencies": ['
        '{"name": "black", "version": "26.5.1", "vulns": []},'
        '{"name": "colorama", "version": "0.4.6", "vulns": ['
        '{"id": "GHSA-fake", "fix_versions": ["0.4.7"]}]}'
        "]}"
    )
    _stub(tmp_path, "uv", f"cat <<'EOF'\n{EXPORT}EOF")
    _stub(tmp_path, "uvx", f"cat <<'EOF'\n{report}\nEOF\nexit 1")

    result = _run(tmp_path)

    assert result.returncode != 0
    assert "colorama 0.4.6: GHSA-fake (fix: 0.4.7)" in result.stdout


@pytest.mark.io
def test_a_package_pinned_at_two_versions_is_audited_at_both(tmp_path):
    # A forked lock: one package, two versions, each behind its own marker.
    # Stripped of the markers they cannot share a requirements file, so the
    # script deals them into two and audits each.
    export = "foo==1.0 ; python_full_version < '3.13'\nfoo==2.0 ; python_full_version >= '3.13'\n"
    _stub(tmp_path, "uv", f"cat <<'EOF'\n{export}EOF")
    # The stub answers for whichever file it was given, as pip-audit would.
    _stub(
        tmp_path,
        "uvx",
        "for argument; do case $argument in *requirements-*.txt) file=$argument;; esac; done\n"
        "version=$(sed -n 's/^foo==//p' \"$file\")\n"
        'printf \'{"dependencies": [{"name": "foo", "version": "%s", "vulns": []}]}\' "$version"',
    )

    result = _run(tmp_path)

    assert result.returncode == 0, result.stdout + result.stderr
    assert "All 2 locked packages audited" in result.stdout


@pytest.mark.io
def test_one_of_two_versions_going_unaudited_is_a_failure(tmp_path):
    export = "foo==1.0 ; python_full_version < '3.13'\nfoo==2.0 ; python_full_version >= '3.13'\n"
    _stub(tmp_path, "uv", f"cat <<'EOF'\n{export}EOF")
    # Always answers for 1.0, whatever it was asked about.
    _stub(tmp_path, "uvx", 'echo \'{"dependencies": [{"name": "foo", "version": "1.0"}]}\'')

    result = _run(tmp_path)

    assert result.returncode != 0
    assert "not audited: foo 2.0" in result.stdout


@pytest.mark.io
def test_the_script_takes_no_arguments(tmp_path):
    _stub(tmp_path, "uv", "exit 1")
    _stub(tmp_path, "uvx", "exit 1")
    environment = dict(os.environ, PATH=f"{tmp_path}{os.pathsep}{os.environ['PATH']}")

    result = subprocess.run(
        [str(AUDIT), "--format", "columns"],
        capture_output=True,
        text=True,
        env=environment,
        cwd=str(ROOT),
    )

    assert result.returncode == 2
    assert "takes no arguments" in result.stderr


@pytest.mark.io
def test_the_whole_locked_set_audited_and_clean_passes(tmp_path):
    report = (
        '{"dependencies": ['
        '{"name": "black", "version": "26.5.1", "vulns": []},'
        '{"name": "colorama", "version": "0.4.6", "vulns": []}'
        "]}"
    )
    _stub(tmp_path, "uv", f"cat <<'EOF'\n{EXPORT}EOF")
    _stub(tmp_path, "uvx", f"cat <<'EOF'\n{report}\nEOF")

    result = _run(tmp_path)

    assert result.returncode == 0, result.stdout + result.stderr
    assert "All 2 locked packages audited" in result.stdout


# ---------------------------------------------------------------------------
# Sign-off: the author's, or that of whoever committed their work
# ---------------------------------------------------------------------------

DCO = ROOT / "scripts" / "check-dco.sh"


def _repository(tmp_path: Path) -> Path:
    """A repository of its own, with the check sitting where it expects to."""
    repository = tmp_path / "repository"
    (repository / "scripts").mkdir(parents=True)
    (repository / "scripts" / "check-dco.sh").write_bytes(DCO.read_bytes())
    (repository / "scripts" / "check-dco.sh").chmod(0o755)
    subprocess.run(["git", "init", "-q", "-b", "main", str(repository)], check=True)
    # A commit to branch from, so that a range can be written at all.
    _commit(repository, "the beginning\n\nSigned-off-by: " + MAINTAINER, MAINTAINER, MAINTAINER)
    return repository


def _commit(repository: Path, message: str, author: str, committer: str) -> None:
    (repository / "file").write_text(message, encoding="utf-8")
    name, _, email = author.partition(" <")
    committer_name, _, committer_email = committer.partition(" <")
    environment = dict(
        os.environ,
        GIT_AUTHOR_NAME=name,
        GIT_AUTHOR_EMAIL=email.rstrip(">"),
        GIT_COMMITTER_NAME=committer_name,
        GIT_COMMITTER_EMAIL=committer_email.rstrip(">"),
    )
    subprocess.run(["git", "add", "file"], cwd=repository, check=True, env=environment)
    subprocess.run(
        ["git", "commit", "-q", "-m", message], cwd=repository, check=True, env=environment
    )


def _check(repository: Path, *arguments):
    return subprocess.run(
        [str(repository / "scripts" / "check-dco.sh"), *arguments],
        capture_output=True,
        text=True,
        cwd=str(repository),
    )


MAINTAINER = "A Maintainer <maintainer@example.com>"
BOT = "dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>"


@pytest.mark.io
def test_the_author_signing_off_is_the_ordinary_case(tmp_path):
    repository = _repository(tmp_path)
    _commit(repository, "a change\n\nSigned-off-by: " + MAINTAINER, MAINTAINER, MAINTAINER)

    result = _check(repository, "HEAD~1..HEAD")

    assert result.returncode == 0, result.stdout + result.stderr
    assert "All 1 commit(s)" in result.stdout


@pytest.mark.io
def test_the_committer_may_sign_off_for_work_they_took_over(tmp_path):
    # `git cherry-pick -s` on a Dependabot commit, as CONTRIBUTING.md
    # describes it: the bot stays the author, the maintainer certifies.
    repository = _repository(tmp_path)
    _commit(repository, "backend: bump black\n\nSigned-off-by: " + MAINTAINER, BOT, MAINTAINER)

    result = _check(repository, "HEAD~1..HEAD")

    assert result.returncode == 0, result.stdout + result.stderr


@pytest.mark.io
def test_a_sign_off_by_neither_of_them_is_not_a_sign_off(tmp_path):
    repository = _repository(tmp_path)
    _commit(
        repository,
        "backend: bump black\n\nSigned-off-by: Someone Else <else@example.com>",
        BOT,
        BOT,
    )

    result = _check(repository, "HEAD~1..HEAD")

    assert result.returncode != 0
    assert "dependabot[bot]" in result.stdout


@pytest.mark.io
def test_a_branch_that_adds_nothing_has_nothing_to_certify(tmp_path):
    repository = _repository(tmp_path)
    _commit(repository, "a change\n\nSigned-off-by: " + MAINTAINER, MAINTAINER, MAINTAINER)

    defaulted = _check(repository)
    asked_for = _check(repository, "HEAD..HEAD")

    assert defaulted.returncode == 0, defaulted.stdout + defaulted.stderr
    assert "nothing to certify" in defaulted.stdout
    assert asked_for.returncode != 0
