# SPDX-License-Identifier: Apache-2.0
# Copyright The Robinauts Authors

"""The inbound side: HTTP in, application calls out, responses back.

It translates and **decides nothing** (``docs/layout.md``): a route reads a
request, calls one application method and turns what comes back into a status,
a body, a cookie or a ``Location``. Every rule it appears to apply -- who may
sign in, whether a return target is safe, what an ID token is worth -- is
applied below it, and every service it uses is handed to it by the composition
root. It depends on ``robinauts.application`` and ``robinauts.domain`` and on
nothing else inside the package.

FastAPI, Starlette and Pydantic live here and in the composition root, and
nowhere else (``docs/specs/backend.md``, "Web"); an import-linter contract in
``backend/pyproject.toml`` says so and the test suite runs it.

What is here: the ``/auth`` routes and ``/health`` (``auth_routes``,
``web``), the conversation routes (``conversation_routes``) and the agents a
conversation is started with (``agent_routes``), what each of them can refuse
with as the OpenAPI document says it (``refusals``), the cookies a sign-in
uses (``cookies``), who is asking and what each route needs of them
(``access``), the checks every write passes before anything reads it
(``protection``), how an error crosses HTTP (``errors``), and the shapes the
JSON API sends (``schemas``).
"""

from robinauts.api.access import (
    FRAMEWORK_PATHS,
    NOT_SIGNED_IN,
    NOT_WIRED,
    PERMISSION_ATTRIBUTE,
    ROUTE_LISTS,
    CurrentUser,
    SignedIn,
    api_routes,
    check_declarations,
    conversing,
    current_user,
    local_access,
    permissions_asked,
    public,
    routes_of,
    signed_in,
    signing_in,
    turning,
    undeclared,
    unknown_route_lists,
)
from robinauts.api.agent_routes import agent_router, list_agents
from robinauts.api.auth_routes import SIGN_IN_PAGE, UI_PATH, auth_router
from robinauts.api.conversation_routes import conversation_router, given_once
from robinauts.api.cookies import (
    HOST_PREFIX,
    LOGIN_COOKIE,
    SESSION_COOKIE,
    clear_cookie,
    cookie_name,
    login_cookie,
    session_cookie,
    set_cookie,
)
from robinauts.api.errors import (
    GENERIC_DETAIL,
    INTERNAL_ERROR,
    MAX_DETAIL_CHARS,
    MAX_LOCATION_CHARS,
    METHOD_NOT_ALLOWED,
    NOT_FOUND_DETAIL,
    NOT_FOUND_ERROR,
    QUIET_RUN_DETAIL,
    SIGN_IN_DETAIL,
    STATUS_OF,
    UNKNOWN_FIELD,
    UNREADABLE_DETAIL,
    UNREADABLE_RULE,
    UNREADABLE_RULES,
    allowed_methods,
    error_body,
    http_error_detail,
    http_error_name,
    install_handlers,
    refusal,
    status_of,
    unknown_fields,
    unreadable_detail,
)
from robinauts.api.logs import MAX_SHOWN, shown
from robinauts.api.protection import (
    BODY_TOO_DEEP,
    BODY_TWICE,
    COOKIE_HEADER,
    CROSS_SITE_DETAIL,
    DECIDING_HEADERS,
    HOST_HEADER,
    LOOPBACK_DETAIL,
    MEDIA_TYPE_DETAIL,
    REPEATED_HEADER_DETAIL,
    SAFE_METHODS,
    SECURITY_HEADERS,
    SITE_ACCEPTED,
    WEBSOCKET_POLICY_VIOLATION,
    Refusal,
    RequestProtection,
    SecurityHeaders,
    StrictJson,
    read_once,
    refused,
    request_headers,
)
from robinauts.api.refusals import (
    ANYTHING_ELSE,
    DELETING,
    LISTING_AGENTS,
    NO_SESSION,
    NOT_JSON,
    NOT_OURS,
    NOT_THERE,
    OPENING,
    READING,
    STILL_ANSWERING,
    UNREADABLE,
    WRITING,
    refusals,
)
from robinauts.api.schemas import (
    AgentListResponse,
    AgentSummary,
    ContentPart,
    ConversationListResponse,
    ConversationSummary,
    EndedBadlyView,
    ErrorResponse,
    HealthResponse,
    MessageView,
    OpenedConversationResponse,
    ProvenanceView,
    ProviderSummary,
    RenameRequest,
    ResumeView,
    RunView,
    SelectLeafRequest,
    SentBadEnd,
    SentKind,
    SentRole,
    SessionResponse,
    UserSummary,
    utc,
)
from robinauts.api.web import (
    API_VERSION,
    BOTH_WAYS,
    OPENAPI_URL,
    TITLE,
    Opening,
    create_api,
    openapi_document,
)
from robinauts.domain import MAX_CAUSES, MAX_FRAMES, chain, where

__all__ = [
    "ANYTHING_ELSE",
    "API_VERSION",
    "BODY_TOO_DEEP",
    "BODY_TWICE",
    "BOTH_WAYS",
    "COOKIE_HEADER",
    "CROSS_SITE_DETAIL",
    "DECIDING_HEADERS",
    "DELETING",
    "FRAMEWORK_PATHS",
    "GENERIC_DETAIL",
    "HOST_HEADER",
    "HOST_PREFIX",
    "INTERNAL_ERROR",
    "LISTING_AGENTS",
    "LOGIN_COOKIE",
    "LOOPBACK_DETAIL",
    "MAX_CAUSES",
    "MAX_DETAIL_CHARS",
    "MAX_FRAMES",
    "MAX_LOCATION_CHARS",
    "MAX_SHOWN",
    "MEDIA_TYPE_DETAIL",
    "METHOD_NOT_ALLOWED",
    "NOT_FOUND_DETAIL",
    "NOT_FOUND_ERROR",
    "NOT_JSON",
    "NOT_OURS",
    "NOT_SIGNED_IN",
    "NOT_THERE",
    "NOT_WIRED",
    "NO_SESSION",
    "OPENAPI_URL",
    "OPENING",
    "PERMISSION_ATTRIBUTE",
    "QUIET_RUN_DETAIL",
    "READING",
    "REPEATED_HEADER_DETAIL",
    "ROUTE_LISTS",
    "SAFE_METHODS",
    "SECURITY_HEADERS",
    "SESSION_COOKIE",
    "SIGN_IN_DETAIL",
    "SIGN_IN_PAGE",
    "SITE_ACCEPTED",
    "STATUS_OF",
    "STILL_ANSWERING",
    "TITLE",
    "UI_PATH",
    "UNKNOWN_FIELD",
    "UNREADABLE",
    "UNREADABLE_DETAIL",
    "UNREADABLE_RULE",
    "UNREADABLE_RULES",
    "WEBSOCKET_POLICY_VIOLATION",
    "WRITING",
    "AgentListResponse",
    "AgentSummary",
    "ContentPart",
    "ConversationListResponse",
    "ConversationSummary",
    "CurrentUser",
    "EndedBadlyView",
    "ErrorResponse",
    "HealthResponse",
    "MessageView",
    "OpenedConversationResponse",
    "Opening",
    "ProvenanceView",
    "ProviderSummary",
    "Refusal",
    "RenameRequest",
    "RequestProtection",
    "ResumeView",
    "RunView",
    "SecurityHeaders",
    "SelectLeafRequest",
    "SentBadEnd",
    "SentKind",
    "SentRole",
    "SessionResponse",
    "SignedIn",
    "StrictJson",
    "UserSummary",
    "agent_router",
    "allowed_methods",
    "api_routes",
    "auth_router",
    "chain",
    "check_declarations",
    "clear_cookie",
    "conversation_router",
    "conversing",
    "cookie_name",
    "create_api",
    "current_user",
    "error_body",
    "given_once",
    "http_error_detail",
    "http_error_name",
    "install_handlers",
    "list_agents",
    "local_access",
    "login_cookie",
    "openapi_document",
    "permissions_asked",
    "public",
    "read_once",
    "refusal",
    "refusals",
    "refused",
    "request_headers",
    "routes_of",
    "session_cookie",
    "set_cookie",
    "shown",
    "signed_in",
    "signing_in",
    "status_of",
    "turning",
    "undeclared",
    "unknown_fields",
    "unknown_route_lists",
    "unreadable_detail",
    "utc",
    "where",
]
